# Generated by Django 4.2.3 on 2023-07-19 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='problemreported',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reports.report'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='production_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pl', to='areas.productionline'),
        ),
    ]
