# Generated by Django 4.2.3 on 2023-07-19 11:58

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_options_problemreported_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemreported',
            name='problem_id',
            field=models.CharField(blank=True, default=reports.models.random_code, max_length=12, unique=True),
        ),
    ]
